### ISSUE TITLE
Tutorial single_rgbd_sensor has "invalid argument source_frame in tf2 frame_ids cannot be empty"

### ISSUE THREAD

**Issue by verdimrc** [spencer-project/spencer_people_tracking#15]
I follow tutorial 1 (`tracking_single_rgbd_sensor.launch`) to run with an RGB-D camera. I made just one change to the tutorial: to replace `ground_plane_tf_based_fixed` with `ground_plane_really_fixed`.

When I run the tutorial, the people detector node (`freiburg_people_tracking.launch`) threw these messages:

```
Warning: Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty
         at line 122 in /tmp/binarydeb/ros-indigo-tf2-0.5.13/src/buffer_core.cpp
[ WARN] [1470824086.900082101]: Failed to lookup transform from frame  into target frame base_footprint! Dropping input DetectedPersons message on topic /spencer/perception_internal/detected_persons/rgbd_front_top/upper_body. Reason: Invalid argument passed to lookupTransform argument source_frame in tf2 frame_ids cannot be empty
Warning: Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty
         at line 122 in /tmp/binarydeb/ros-indigo-tf2-0.5.13/src/buffer_core.cpp
```

Any idea what could be possibly wrong? I went through `freiburg_people_tracking.launch` and noticed some references to high precision lasers; could this device be mandatory for tutorial 1?

**Comment by tlind** [comment]
I think this issue was caused by your use of `ground_plane_really_fixed`. There might be some ROS message header `frame_id` not being set correctly in that node, as we did not use it in our experiments.
