### ISSUE TITLE
Try to compile the package on Ubuntu 12.04

### ISSUE THREAD

**Issue by SubAerian** [spencer-project/spencer_people_tracking#18]
Hi,

When I try to compile the packages on Ubuntu 12.04, I get the following error : 

`In file included from /home/wcolin/repos/monarch_git/svn_repository/monarch/code/trunk/catkin_ws/src/spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/include/srl_nearest_neighbor_tracker/data/polygon_boost.h:33:0,
                 from /home/wcolin/repos/monarch_git/svn_repository/monarch/code/trunk/catkin_ws/src/spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/include/srl_nearest_neighbor_tracker/occlusion_handling/polygon_occlusion_manager.h:56,
                 from /home/wcolin/repos/monarch_git/svn_repository/monarch/code/trunk/catkin_ws/src/spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/src/srl_nearest_neighbor_tracker/nearest_neighbor_tracker.cpp:39:
/home/wcolin/repos/monarch_git/svn_repository/monarch/code/trunk/catkin_ws/src/spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/include/srl_nearest_neighbor_tracker/data/point_boost.h:34:39: fatal error: boost/geometry/geometry.hpp: No such file or directory
compilation terminated.
animated_markers/animated_marker_rviz_plugin/CMakeFiles/animated_marker_rviz_plugin.dir/src/marker_array_display.cpp.o
Scanning dependencies of target spencer_tracking_rviz_plugin
make[2]: *** [spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/CMakeFiles/nnt_node.dir/src/srl_nearest_neighbor_tracker/nearest_neighbor_tracker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [spencer_people_tracking/tracking/people/srl_nearest_neighbor_tracker/CMakeFiles/nnt_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

I saw on internet this is linked to the version of boost. But the latest version of boost on Ubuntu 12.04 is the version 1.46 instead of the version 1.47. Do you know how may I fix it ?

Best,

**Comment by tlind** [comment]
Sorry, Ubuntu 12.04 is not supported anymore in the current version. You need at least Ubuntu 14.04. You would have to roll back the srl_nearest_neighbor_tracker package to commit 6380209ba, but then you will also lose some other functionality and other things might break.
