### ISSUE TITLE
cannot compile in kinect

### ISSUE THREAD

**Issue by zubair123khan** [spencer-project/spencer_people_tracking#29]
hi folks, 

i am using ros kinect and i am not able to compile spencer_tracking .. it need hell amount of libraries which diesnt come with the installation,,
i am is there any way to install all the libraries which is in use with spencer_tracking once for all,,??

please help

**Comment by tlind** [comment]
Hi,

you can try the following commands after cloning the repository into your ROS workspace's `src` folder:

    rosdep update
    rosdep install --simulate -r --from-paths PATH_TO_YOUR_SRC_FOLDER --ignore-src

If everything looks good, remove the `--simulate` to actually execute it. Note I couldn't test this as I already have all dependencies installed on my system.

Before doing so please `git pull` once, as I just fixed a small bug related to `rosdep` in the master branch.

**Comment by tlind** [comment]
I have added a few missing dependencies to various `package.xml` files required for compilation to succeed under ROS Kinetic. The above instructions using `rosdep install` should now do the trick.
