### ISSUE TITLE
Stereo Vision compatibility

### ISSUE THREAD

**Issue by archenroot** [spencer-project/spencer_people_tracking#44]
Hi guys,

first of all thank you for this impressive work. 

I would like to ask you if and how difficult it will be to work with stereo camera setup? What is the RGB-D data format you support? I am not asking for detailed guidance, just for hints if possible.

Thank you.

Ladislav

**Comment by archenroot** [comment]
This is quite clear, as soon as I can provide RBG-D signal, it will be compatible, I will look how to bridge it by myself....

**Comment by tlind** [comment]
If you use the upper-body detector, it has been trained for a depth image resolution of 640 x 480 pixels. This might be worth to consider.
