### ISSUE TITLE
cannot CMake 

### ISSUE THREAD

**Issue by dahlan77** [spencer-project/spencer_people_tracking#46]
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find LibSVM (missing: LIBSVM_LIBRARY LIBSVM_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  spencer_people_tracking/tracking/groups/spencer_social_relations/cmake/FindLibSVM.cmake:126 (find_package_handle_standard_args)
  spencer_people_tracking/tracking/groups/spencer_social_relations/CMakeLists.txt:37 (find_package)

**Comment by tlind** [comment]
Just run `sudo apt-get install libsvm-dev` on Ubuntu.
