### ISSUE TITLE
what is the reference frame of the pose in TrackedPerson.msg?

### ISSUE THREAD

**Issue by CxyCH** [spencer-project/spencer_people_tracking#48]
Hello Sir:
    This is a great project and help me a lot. I want to use the pose of the TrackedPerson to build a costmap but I can't find any information about the reference frame of the trackedperson. 
    I am launching tracking_on_bagfile.launch, and rewrite the human_attributes.py in the spencer_perception_mocks by using the TrackedPerson.msg information directly to display the distance between person and robot, but the value is wrong. So can you tell me what is the reference frame of the pose in TrackedPerson.msg? the /map, /odom, /robot or /sensor? 
    Thank you very much.

**Comment by tlind** [comment]
The reference frame being used may depend on the actual tracker implementation, and is specified in header.frame_id of the published TrackedPersons message. Thus, you can look up the frame_id for each message you receive (though the frame should not change in between messages), and then use a TransformListener to transform the poses into your desired frame.

In practice, the srl_nearest_neighbor_tracker publishes its output in "odom" frame.
