### ISSUE TITLE
Upper body template generation

### ISSUE THREAD

**Issue by Kapcirt** [spencer-project/spencer_people_tracking#56]
Hello,
I have a problem with the upper body detection, the camera that I'm using is fixed at 1m71 with an orientation of 12 degree towards the ground. This makes the detection almost impossible since most of the time the head is cropped in the middle of the depth image. 

The solution that I found for now was to crop myself the upper body template, and then to copy the last line until the dimension of the template was correct : https://raw.githubusercontent.com/Kapcirt/spencer_people_tracking/stockbot-changes/detection/rgbd_detectors/rwth_upper_body_detector/config/upper_temp_n2.txt
But I was wondering how you generated the upperbody template so I can have a better template for my situation.

Thanks for your help

**Comment by tlind** [comment]
Sorry, I do not have any details on this -- you might want to contact the original authors of the upper body detector at RWTH Aachen.
