### ISSUE TITLE
Can‘t work at slaver machine when fuse the laser and rgbd information

### ISSUE THREAD

**Issue by CxyCH** [spencer-project/spencer_people_tracking#57]
Hi:
   I met a very wired problem.
   When I only use the rgbd camera, it can work normally on the host or the slave machine. The tf information of rgbd camera is directly published through openni. 
   When I use the laser and rgbd at the same time, this package can only work on the host machine normally that the laser's tf published here, but on the slave machine, it will fail when the program goes to the fusing step(the upper body detector and leg detector can work well and the slave machine can subscribe /tf topic at ~80hz, and subscribe the /tf_static at ~1500hz，the laser information at ~50hz).

   I use the same launch file, so what’s wrong here？

**Comment by tlind** [comment]
This could be a time synchronization issue... make sure that you have correctly synchronized the clocks of both computers using chrony/ntpdate.
