### ISSUE TITLE
can retrain?

### ISSUE THREAD

**Issue by gongyue666** [spencer-project/spencer_people_tracking#58]
Can the detector be retrained by my own dataset? 
By the way there are too many nodes and .launch files, do they all needed?Seem too large for me

**Comment by tlind** [comment]
Which detector?
The launch files and nodes are provided for maximum flexibility and deployment of different kinds of robots. This is a relatively generic framework for person tracking from (mobile) robots, not an application tailored to a specific robot.

**Comment by CodeToPoem** [comment]
Hello,
I have a problem with the 'groups_probabilistic_small.model' in 'spencer_social_relations'. Can I see the origin datasets that used to retrain svm model?

**Comment by tlind** [comment]
I think I might still have an annotated CARMEN logfile of the groundtruth tracks/groups. Give me some time to dig that out from an old computer. I cannot share the visual data (camera image stream) for privacy ressons.

**Comment by CodeToPoem** [comment]
Thanks a lot. @tlind

**Comment by tlind** [comment]
I am responding to the SVM-related questions in #63.
Closing this issue because original author did not reply any further.
