### ISSUE TITLE
Why the walking person model's ID number in RVIZ is not successive ?

### ISSUE THREAD

**Issue by AssassinCrow** [spencer-project/spencer_people_tracking#72]
I finally succeeded in drawing the walking person model.

But in [my case](https://youtu.be/erqV4Rjq6cs), the ID number of each person in the RVIZ displayer is not successive.

I don't know why they are not successive.

The track_id of 'trackedPerson' topic corresponds to the ID number (e.g. [MATCHED 0] or [MISSED 2]) of the walking person model in the RVIZ  right?

Then what is the criterion of whether the model would be displayed or not in the RVIZ?

Thanks in advance :)

**Comment by tlind** [comment]
Hi,
that is indeed a good question. Normally IDs should be consecutive (though some IDs may appear just very briefly). In your terminal window, I see a track ID 2, but I do not see the corresponding visualization in Rviz. Maybe it is outside of the Rviz camera's field of view (i.e. not visible unless you zoom out)? You could also open up the "Status" of the "TrackedPersons" display to see how many tracks are currently active/received.
