### ISSUE TITLE
Are the detected & tracted pose values in Global frame or spencer's Local frame?

### ISSUE THREAD

**Issue by AssassinCrow** [spencer-project/spencer_people_tracking#73]
I just want to get confirmation from you.

I've read almost all the source codes and never found the codes wrt conversion of coordinates between spencer's local coordinates and global world frame.
So I think those are in the robot's local coordinate frame.
I also think since spencer would never move in opened source on github, so it is not necessary to consider conversion.

Is it correct?

**Comment by tlind** [comment]
Detection occurs in sensor frame, but tracking in odom frame which is fixed (up to odometry drift). The transformation occurs in srl_nearest_neighbor_tracker / ros_interface.cpp + geometry_utils.cpp.
