### ISSUE TITLE
Dataset Motion Capture

### ISSUE THREAD

**Issue by TPCWester** [spencer-project/spencer_people_tracking#76]
For my research I would like to get acces to the Motion Capture data set with ground-truth annotation. Could you maybe send this to my email: t.p.c.wester@student.tue.nl?

**Comment by FooKii** [comment]
hi, i will also be interested. my email: ga26mib@tum.de
And thanks for the package and framework, as a rookie, i would really appreciate a quick tutorial on spencer_tracking_metrics.  

So far my understanding is for [clearmot_from_logfile.launch](https://github.com/spencer-project/spencer_people_tracking/blob/master/tracking/people/spencer_tracking_metrics/launch/clearmot_from_logfile.launch) is:
* /ground truth from [srl_tracking_logfile_import](https://github.com/spencer-project/spencer_people_tracking/tree/master/tracking/people/srl_tracking_logfile_import), but the link for downloading CARMEN logfile is broken.
* detector running online, and result will be compared (evaluated) with the ground truth. 

As for another [clearmot_laser_detector.launch](https://github.com/spencer-project/spencer_people_tracking/blob/bcde8b78ea07f65920966a4d659ba8ef61aed9bc/tracking/people/spencer_tracking_metrics/launch/clearmot_laser_detector.launch):
* you can record your detection result in a bag file
* and your bag file will be evaluated with the groundtruth directly from pedsim.
* however, in code ```<remap from="/groundtruth" to="/tracks_with_simulated_occlusions"/>```, what does simulated occlusion mean? Does it mean that occlusion from pedsim will be removed as it's then impossible for detection from sensors, hence not count as false-positive if detector get it wrong.

So the requested annotated data should be for the clearmot_from_logfile data, am i right?

Many Thanks
