### ISSUE TITLE
python listener

### ISSUE THREAD

**Issue by jonathanleinola** [spencer-project/spencer_people_tracking#89]
Hey,
could you point me out how to do a python listener for the matched object? I could not find for how to listen for eg. this topic: /spencer/perception/tracked_persons/tracks. Tried with: rospy.Subscriber('/spencer/perception/tracked_persons/tracks/pose/pose', Pose, callback), but i think it's not right.

Also, can i somehow extract the velocity parameters too?

Thank you

**Comment by tlind** [comment]
You need to use `TrackedPersons' as the second argument. And import it:

    from spencer_tracking_msgs.msg import TrackedPersons, TrackedPerson

You can get the estimated linear velocity using trackedPerson.twist.twist.linear.x and .y

**Comment by jonathanleinola** [comment]
Thank you!

**Comment by jonathanleinola** [comment]
Hi, is it possible to get the trackedperson in map frame too somehow? if I have a camera mounted on top of a robot?
