### ISSUE TITLE
Get detected person coordinates in a map coordinate system

### ISSUE THREAD

**Issue by jonathanleinola** [spencer-project/spencer_people_tracking#90]
Hi,

Is it somehow possible to get the detected person coordinates in map coordinates? if i switch the dummy transformation to in relate to base_link, the coordinates of the detected person is still at in relation to the camera coordinates. For eg. if the robot's base_link is at (10,10) and the human is at (1,0) then then human should be at (11,10)? i know i can calculate that using a listener but i think my camera is not updating it's position -also thought this might automatically update it's position then? or should i modify some other transformation too?

Greetings,
Jonathan

**Comment by jonathanleinola** [comment]
I am able to link it with the robot's baselink. the positions of tracked person seems right, but the tracking get affected by the frequency of the published baselink topic. any help?

**Comment by tlind** [comment]
The tracker always has to wait for the transform from odom to base_link to arrive, before it can transform the detections into the fixed world frame. You could increase the publish frequency by interpolating the transforms, or dating the timestamp of the published transform a bit into the future so the tracker does not have to wait for it to arrive.

**Comment by jonathanleinola** [comment]
Oh, interesting. i will take a look on that. What if i connect them both to robot's base_link? the base_footprint_id and world_frame_id. i seem not understand the difference of these frames
