### ISSUE TITLE
People tracking process dies

### ISSUE THREAD

**Issue by jonathanleinola** [spencer-project/spencer_people_tracking#96]
Hi, 

Do you have an idea why the people tracking module crashes when the detection from the upper body is lost? And what could i do with it. Can i somehow reset the tracking module?
Error:
[spencer/perception_internal/people_tracking/post_processing/filter_tracks_confirmed_by_upper_body-36] process has died [pid 4515, exit code -11]

**Comment by Alex-Beh** [comment]
The tracking process didn't die. Only the filter module die because of some bug inside the code. You can refer to [this commit](https://github.com/PhiAbs/spencer_people_tracking_yolo/commit/fa543f0649e5388884cc95e2dafa92d0dd6f073a).

**Comment by jonathanleinola** [comment]
Awesome, thanks for pointing me in the right direction. I'll go through it and see if I can find it

**Comment by kaushikbalasundar** [comment]
@jonathanleinola were you able to solve this bug?
